/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 2.0.1
 */

export type PutTodo200 = {
    /** The id of the newly created todo item */
    id: string;
};
