/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AccountRouteImport } from './routes/account'

const MuiLazyRouteImport = createFileRoute('/mui')()
const IndexLazyRouteImport = createFileRoute('/')()

const MuiLazyRoute = MuiLazyRouteImport.update({
  id: '/mui',
  path: '/mui',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/mui.lazy').then((d) => d.Route))
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/todo': typeof TodoRoute
  '/mui': typeof MuiLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/todo': typeof TodoRoute
  '/mui': typeof MuiLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/todo': typeof TodoRoute
  '/mui': typeof MuiLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/chat' | '/todo' | '/mui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/chat' | '/todo' | '/mui'
  id: '__root__' | '/' | '/account' | '/chat' | '/todo' | '/mui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AccountRoute: typeof AccountRoute
  ChatRoute: typeof ChatRoute
  TodoRoute: typeof TodoRoute
  MuiLazyRoute: typeof MuiLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mui': {
      id: '/mui'
      path: '/mui'
      fullPath: '/mui'
      preLoaderRoute: typeof MuiLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AccountRoute: AccountRoute,
  ChatRoute: ChatRoute,
  TodoRoute: TodoRoute,
  MuiLazyRoute: MuiLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
