/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodoImport } from './routes/todo'
import { Route as AccountImport } from './routes/account'

// Create Virtual Routes

const MuiLazyImport = createFileRoute('/mui')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MuiLazyRoute = MuiLazyImport.update({
  id: '/mui',
  path: '/mui',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mui.lazy').then((d) => d.Route))

const TodoRoute = TodoImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoImport
      parentRoute: typeof rootRoute
    }
    '/mui': {
      id: '/mui'
      path: '/mui'
      fullPath: '/mui'
      preLoaderRoute: typeof MuiLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/account': typeof AccountRoute
  '/todo': typeof TodoRoute
  '/mui': typeof MuiLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/account': typeof AccountRoute
  '/todo': typeof TodoRoute
  '/mui': typeof MuiLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/account': typeof AccountRoute
  '/todo': typeof TodoRoute
  '/mui': typeof MuiLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/todo' | '/mui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/todo' | '/mui'
  id: '__root__' | '/' | '/account' | '/todo' | '/mui'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AccountRoute: typeof AccountRoute
  TodoRoute: typeof TodoRoute
  MuiLazyRoute: typeof MuiLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AccountRoute: AccountRoute,
  TodoRoute: TodoRoute,
  MuiLazyRoute: MuiLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account",
        "/todo",
        "/mui"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/account": {
      "filePath": "account.tsx"
    },
    "/todo": {
      "filePath": "todo.tsx"
    },
    "/mui": {
      "filePath": "mui.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
